-- Discord bot integration: account linking (phase 0) plus the storage the AI Bug
-- Analyzer, Suggestion System, Ticket Assistant, and Changelog Generator write to
-- (phases 1-3). Every table here is written exclusively by the bot's service-role
-- client (same pattern as usage_events/subscriptions in 006_credits_and_usage.sql) —
-- there is no end-user session that should ever see or touch these rows directly, so
-- RLS is enabled with no policies (deny-by-default) rather than user-scoped SELECT
-- policies.

CREATE TABLE IF NOT EXISTS discord_accounts (
  discord_user_id VARCHAR(32) PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  linked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discord_accounts_user_id ON discord_accounts(user_id);

-- Short-lived one-time codes generated by the web dashboard ("Connect Discord"
-- button, phase 4 follow-up) and redeemed by /link. Deleted on redemption.
CREATE TABLE IF NOT EXISTS link_codes (
  code VARCHAR(16) PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bug_reports (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  discord_user_id VARCHAR(32) NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  screenshot_urls TEXT[] DEFAULT '{}',
  repro_steps TEXT,
  category VARCHAR(50) CHECK (category IN ('frontend', 'backend', 'database', 'ai', 'api', 'authentication', 'performance', 'security', 'other')),
  severity VARCHAR(20) CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  priority VARCHAR(20) CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  ai_summary TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'triaged', 'resolved', 'wont_fix')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bug_reports_status ON bug_reports(status);
CREATE INDEX IF NOT EXISTS idx_bug_reports_created_at ON bug_reports(created_at);

CREATE TABLE IF NOT EXISTS suggestions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  discord_user_id VARCHAR(32) NOT NULL,
  title_raw TEXT NOT NULL,
  title_ai TEXT,
  description_ai TEXT,
  tags TEXT[] DEFAULT '{}',
  duplicate_of UUID REFERENCES suggestions(id) ON DELETE SET NULL,
  votes_up INTEGER NOT NULL DEFAULT 0,
  votes_down INTEGER NOT NULL DEFAULT 0,
  -- Maps discord_user_id -> 'up' | 'down', so a repeat click toggles/switches the vote
  -- instead of stacking (see services/suggestions.ts recordVote).
  voters JSONB NOT NULL DEFAULT '{}'::jsonb,
  message_id VARCHAR(32),
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'planned', 'shipped', 'declined')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Belt-and-suspenders for anyone who already ran this file before `voters` was added:
-- CREATE TABLE IF NOT EXISTS is a no-op on an existing table, so the ADD COLUMN below is
-- what actually backfills it on a rerun.
ALTER TABLE suggestions ADD COLUMN IF NOT EXISTS voters JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_suggestions_status ON suggestions(status);
CREATE INDEX IF NOT EXISTS idx_suggestions_created_at ON suggestions(created_at);

CREATE TABLE IF NOT EXISTS support_tickets (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  discord_user_id VARCHAR(32) NOT NULL,
  thread_id VARCHAR(32),
  ai_summary TEXT,
  transcript JSONB DEFAULT '[]',
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  resolved_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);

CREATE TABLE IF NOT EXISTS changelog_entries (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  period_label VARCHAR(100) NOT NULL,
  features JSONB DEFAULT '[]',
  improvements JSONB DEFAULT '[]',
  fixes JSONB DEFAULT '[]',
  security JSONB DEFAULT '[]',
  published_message_id VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE discord_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bug_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE changelog_entries ENABLE ROW LEVEL SECURITY;
